# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vihangifernando/Desktop/mollybet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vihangifernando/Desktop/mollybet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vihangifernando/Desktop/mollybet/CMakeFiles /Users/vihangifernando/Desktop/mollybet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vihangifernando/Desktop/mollybet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named molly_api_client

# Build rule for target.
molly_api_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 molly_api_client
.PHONY : molly_api_client

# fast build rule for target.
molly_api_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/build
.PHONY : molly_api_client/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named curl_uninstall

# Build rule for target.
curl_uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl_uninstall
.PHONY : curl_uninstall

# fast build rule for target.
curl_uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/CMakeFiles/curl_uninstall.dir/build.make _deps/curl-build/CMakeFiles/curl_uninstall.dir/build
.PHONY : curl_uninstall/fast

#=============================================================================
# Target rules for targets named man

# Build rule for target.
man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 man
.PHONY : man

# fast build rule for target.
man/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/libcurl/CMakeFiles/man.dir/build.make _deps/curl-build/docs/libcurl/CMakeFiles/man.dir/build
.PHONY : man/fast

#=============================================================================
# Target rules for targets named opts-man

# Build rule for target.
opts-man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opts-man
.PHONY : opts-man

# fast build rule for target.
opts-man/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/libcurl/opts/CMakeFiles/opts-man.dir/build.make _deps/curl-build/docs/libcurl/opts/CMakeFiles/opts-man.dir/build
.PHONY : opts-man/fast

#=============================================================================
# Target rules for targets named libcurl_shared

# Build rule for target.
libcurl_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl_shared
.PHONY : libcurl_shared

# fast build rule for target.
libcurl_shared/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build
.PHONY : libcurl_shared/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) $(MAKESILENT) -f cpr/cpr/CMakeFiles/cpr.dir/build.make cpr/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

src/HTTPClient.o: src/HTTPClient.cpp.o
.PHONY : src/HTTPClient.o

# target to build an object file
src/HTTPClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/HTTPClient.cpp.o
.PHONY : src/HTTPClient.cpp.o

src/HTTPClient.i: src/HTTPClient.cpp.i
.PHONY : src/HTTPClient.i

# target to preprocess a source file
src/HTTPClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/HTTPClient.cpp.i
.PHONY : src/HTTPClient.cpp.i

src/HTTPClient.s: src/HTTPClient.cpp.s
.PHONY : src/HTTPClient.s

# target to generate assembly for a file
src/HTTPClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/HTTPClient.cpp.s
.PHONY : src/HTTPClient.cpp.s

src/MollyAPIClient.o: src/MollyAPIClient.cpp.o
.PHONY : src/MollyAPIClient.o

# target to build an object file
src/MollyAPIClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/MollyAPIClient.cpp.o
.PHONY : src/MollyAPIClient.cpp.o

src/MollyAPIClient.i: src/MollyAPIClient.cpp.i
.PHONY : src/MollyAPIClient.i

# target to preprocess a source file
src/MollyAPIClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/MollyAPIClient.cpp.i
.PHONY : src/MollyAPIClient.cpp.i

src/MollyAPIClient.s: src/MollyAPIClient.cpp.s
.PHONY : src/MollyAPIClient.s

# target to generate assembly for a file
src/MollyAPIClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/MollyAPIClient.cpp.s
.PHONY : src/MollyAPIClient.cpp.s

src/WebSocketClient.o: src/WebSocketClient.cpp.o
.PHONY : src/WebSocketClient.o

# target to build an object file
src/WebSocketClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/WebSocketClient.cpp.o
.PHONY : src/WebSocketClient.cpp.o

src/WebSocketClient.i: src/WebSocketClient.cpp.i
.PHONY : src/WebSocketClient.i

# target to preprocess a source file
src/WebSocketClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/WebSocketClient.cpp.i
.PHONY : src/WebSocketClient.cpp.i

src/WebSocketClient.s: src/WebSocketClient.cpp.s
.PHONY : src/WebSocketClient.s

# target to generate assembly for a file
src/WebSocketClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/WebSocketClient.cpp.s
.PHONY : src/WebSocketClient.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/molly_api_client.dir/build.make CMakeFiles/molly_api_client.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... curl_uninstall"
	@echo "... man"
	@echo "... opts-man"
	@echo "... cpr"
	@echo "... libcurl_shared"
	@echo "... molly_api_client"
	@echo "... zlib"
	@echo "... src/HTTPClient.o"
	@echo "... src/HTTPClient.i"
	@echo "... src/HTTPClient.s"
	@echo "... src/MollyAPIClient.o"
	@echo "... src/MollyAPIClient.i"
	@echo "... src/MollyAPIClient.s"
	@echo "... src/WebSocketClient.o"
	@echo "... src/WebSocketClient.i"
	@echo "... src/WebSocketClient.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

